# Generated by Django 4.2.2 on 2023-06-23 14:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Immobilier', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bookings',
            old_name='residenceId',
            new_name='residence',
        ),
        migrations.RenameField(
            model_name='bookings',
            old_name='userId',
            new_name='user',
        ),
        migrations.RenameField(
            model_name='medias',
            old_name='residenceId',
            new_name='residence',
        ),
        migrations.RenameField(
            model_name='optionresidences',
            old_name='optionId',
            new_name='option',
        ),
        migrations.RenameField(
            model_name='optionresidences',
            old_name='residenceId',
            new_name='residence',
        ),
        migrations.RenameField(
            model_name='reviews',
            old_name='residenceId',
            new_name='residence',
        ),
        migrations.RenameField(
            model_name='reviews',
            old_name='userId',
            new_name='user',
        ),
    ]
