# Generated by Django 4.2.2 on 2023-06-23 22:25

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('Immobilier', '0002_rename_residenceid_bookings_residence_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ApartmentOptions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Apartments',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True)),
                ('apartmentNumber', models.CharField(max_length=45)),
                ('pieceNumber', models.IntegerField()),
                ('bathroomNumber', models.IntegerField()),
                ('bedNumber', models.IntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now_add=True)),
                ('residence', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Immobilier.residences')),
            ],
        ),
        migrations.DeleteModel(
            name='OptionResidences',
        ),
        migrations.AddField(
            model_name='apartmentoptions',
            name='apartment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Immobilier.apartments'),
        ),
        migrations.AddField(
            model_name='apartmentoptions',
            name='option',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Immobilier.options'),
        ),
    ]
